BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 20
  EPOCHS: 30
  LR: 9e-3
  WD: 1e-2
  EARLY_STOPPING_EPOCHS: 3
  MODEL_FILE_NAME: VitalLens_Physnet_NegLogLikelihood%%MODEL_NAME_EXTENSION%%
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: VitalVideos_and_UBFC
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/data"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/results/preprocessed_rppgToolbox"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    COMPRESSION_FORMAT: 'NPZ'
    # Locations: B: [0.0, 0.07]; KL: [0.07, 0.155]; KLL: [0.155, 0.7]; KU: [0.7, 0.77]; KUL: [0.77, 0.86]; T: [0.86, 0.935]; WSZ: [0.935, 1.0] # validation split WSZ location
    BEGINS: [0.0, 0.0]      # Train split
    ENDS: [0.7, 1.0]
    #BEGINS: [0.86, 0.0]   # Validation split
    #ENDS: [1.0, 0.0]
    #BEGINS: [0.7, 0.0]   # Test split
    #ENDS: [0.86, 0.0]
    BEGIN: 0.0
    END: 1.0
    DATA_AUG: ["Torchvision brightness 0.8 1.2"] #"Torchvision hue -0.05 0.05", "Torchvision brightness 0.2 2.0", "Torchvision contrast 0.2 2.0", "Torchvision saturation 0.2 2.0", "Torchvision sharpness 0.5 1.5"
    CACHE_UNCOMPRESSED: "/mnt/usb/cache_rppg_toolbox"
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized','Standardized']
      CONVERT_TO_TYPE: 'DiffNormalized'
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      #CONVERT_TO_TYPE: 'DiffNormalized'
      DO_CHUNK: True
      CHUNK_LENGTH: 160  #only support for factor of 512
      ARTIFICIAL_DESTABILISATION_BACKEND: '%%DESTAB_BACKEND%%'
      ARTIFICIAL_DESTABILISATION_AMPLITUDE: %%DESTAB_AMPLITUDE%%
      DEEPSTAB_PREPROCESSED_PATH: "/mnt/results/deepstab"
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: '%%STABILIZATION_BACKEND%%'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : %%DD_FREQUENCY%%
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: %%SIZE%%
        W: %%SIZE%%
        ADDITIONAL_SIZES: %%ADDITIONAL_SIZES%%  # Additional sizes for resizing, if needed
VALID:
  DATA:
    FS: 30
    DATASET: VitalVideos_and_UBFC
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/data"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/results/preprocessed_rppgToolbox"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    COMPRESSION_FORMAT: 'NPZ'
    # Locations: B: [0.0, 0.07]; KL: [0.07, 0.155]; KLL: [0.155, 0.7]; KU: [0.7, 0.77]; KUL: [0.77, 0.86]; T: [0.86, 0.935]; WSZ: [0.935, 1.0] # validation split WSZ location
    #BEGINS: [0.0, 0.0]      # Train split
    #ENDS: [0.7, 1.0]
    BEGINS: [0.86, 0.0]   # Validation split
    ENDS: [1.0, 0.0]
    #BEGINS: [0.7, 0.0]   # Test split
    #ENDS: [0.86, 0.0]
    BEGIN: 0.0
    END: 1.0
    #DATA_AUG: ["RandomFrameShuffle 0.5"] #"Torchvision hue -0.05 0.05", "Torchvision brightness 0.2 2.0", "Torchvision contrast 0.2 2.0", "Torchvision saturation 0.2 2.0", "Torchvision sharpness 0.5 1.5"
    CACHE_UNCOMPRESSED: "/mnt/usb/cache_rppg_toolbox"
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      CONVERT_TO_TYPE: 'DiffNormalized'
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160  #only support for factor of 512
      ARTIFICIAL_DESTABILISATION_BACKEND: '%%DESTAB_BACKEND%%'
      ARTIFICIAL_DESTABILISATION_AMPLITUDE: %%DESTAB_AMPLITUDE%%
      DEEPSTAB_PREPROCESSED_PATH: "/mnt/results/deepstab"
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: '%%STABILIZATION_BACKEND%%'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : %%DD_FREQUENCY%%
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: %%SIZE%%
        W: %%SIZE%%
        ADDITIONAL_SIZES: %%ADDITIONAL_SIZES%%  # Additional sizes for resizing, if needed
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: VitalVideos_and_UBFC
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/data"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/results/preprocessed_rppgToolbox"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    COMPRESSION_FORMAT: 'NPZ'
    # Locations: B: [0.0, 0.07]; KL: [0.07, 0.155]; KLL: [0.155, 0.7]; KU: [0.7, 0.77]; KUL: [0.77, 0.86]; T: [0.86, 0.935]; WSZ: [0.935, 1.0] # validation split WSZ location
    #BEGINS: [0.0, 0.0]      # Train split
    #ENDS: [0.7, 1.0]
    #BEGINS: [0.86, 0.0]   # Validation split
    #ENDS: [1.0, 0.0]
    BEGINS: [0.7, 0.0]   # Test split
    ENDS: [0.86, 0.0]
    BEGIN: 0.0
    END: 1.0
    CACHE_UNCOMPRESSED: "/mnt/usb/cache_rppg_toolbox"
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      CONVERT_TO_TYPE: 'DiffNormalized'
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160  #only support for factor of 512
      ARTIFICIAL_DESTABILISATION_BACKEND: '%%DESTAB_BACKEND%%'
      ARTIFICIAL_DESTABILISATION_AMPLITUDE: %%DESTAB_AMPLITUDE%%
      DEEPSTAB_PREPROCESSED_PATH: "/mnt/results/deepstab"
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: '%%STABILIZATION_BACKEND%%'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : %%DD_FREQUENCY%%
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: %%SIZE%%
        W: %%SIZE%%
        ADDITIONAL_SIZES: %%ADDITIONAL_SIZES%%  # Additional sizes for resizing, if needed
DEVICE: cuda:1
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/%%EXP_NAME%%
MODEL:
  DROP_RATE: 0.2
  NAME: PhysNetUncertainty
  PHYSNET:
    FRAME_NUM: 160
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH:   ""
