BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True
  DATA:
    FS: 30
    DATASET: Emergency_Videos
    DO_PREPROCESS: True                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/mnt/data/emergencyVideos"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/mnt/results/preprocessed_rppgToolbox/emergency"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    COMPRESSION_FORMAT: 'NPZ'
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      VIDEO_SUBSET_TO_USE: [10.0, 9999.0]   # get rid of the first 10 seconds of the video
      DATA_TYPE: [ 'DiffNormalized','Standardized' ] #if use physnet, should be DiffNormalized
      CONVERT_TO_TYPE: 'Standardized'
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160  #only support for factor of 512
      ARTIFICIAL_DESTABILISATION_BACKEND: '%%DESTAB_BACKEND%%'
      ARTIFICIAL_DESTABILISATION_AMPLITUDE: %%DESTAB_AMPLITUDE%%
      DEEPSTAB_PREPROCESSED_PATH: "/mnt/results/deepstab"
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: '%%STABILIZATION_BACKEND%%'    # HC for Haar Cascade, RF for RetinaFace, Y5F for YOLO5Face
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: True
          DYNAMIC_DETECTION_FREQUENCY : %%DD_FREQUENCY%%
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: %%SIZE%%
        W: %%SIZE%%
        ADDITIONAL_SIZES: %%ADDITIONAL_SIZES%%  # Additional sizes for resizing, if needed
DEVICE: cuda:1
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/%%EXP_NAME%%
MODEL:
  DROP_RATE: 0.2
  NAME: None
  EFFICIENTPHYS:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH:   ""  # Path to the model file, should be updated with the actual path
